#include <iostream>
#include <vector>
using namespace std;

/*
===========================================================
389. Find the Difference
===========================================================

Problem:
You are given two strings s and t.

String t is generated by randomly shuffling string s
and then adding one extra character at a random position.

Return the extra character.

Example:
Input:
s = "abcd"
t = "abcde"

Output:
'e'

-----------------------------------------------------------
IDEA
-----------------------------------------------------------

Both strings contain the same characters except that
t contains one additional character.

If we calculate the sum of ASCII values of all characters
in both strings:

    extraCharacter = sum(t) - sum(s)

The difference will be the ASCII value of the extra
character.

-----------------------------------------------------------
APPROACH
-----------------------------------------------------------

1. Compute the ASCII sum of all characters in s.
2. Compute the ASCII sum of all characters in t.
3. Subtract the two sums.
4. Convert the resulting ASCII value back to a character.

-----------------------------------------------------------
TIME COMPLEXITY
-----------------------------------------------------------

O(n)

where n = length of s.

-----------------------------------------------------------
SPACE COMPLEXITY
-----------------------------------------------------------

O(1)

Only a few variables are used.

===========================================================
*/

class Solution {
public:
    char findTheDifference(string s, string t) {
        int n = s.size();

        int sumS = 0;
        int sumT = 0;

        // Calculate ASCII sum of s
        for (int i = 0; i < n; i++) {
            sumS += s[i];
        }

        // Calculate ASCII sum of t
        for (int i = 0; i < n + 1; i++) {
            sumT += t[i];
        }

        // Difference gives the extra character
        return sumT - sumS;
    }
};